### ISSUE TITLE
Regarding Assistant and Tone Analyzer Integration Example

### ISSUE THREAD

**Issue by diana-RC** [watson-developer-cloud/python-sdk#697]
Hi ,
I am trying to run the Assistant and Tone Analyzer Integration Example in python sdk and I am getting the following errors

```
 File "tone_assistant_integration.v1.py", line 71, in <module>
    invokeToneConversation(global_payload, global_maintainToneHistoryInContext)
  File "tone_assistant_integration.v1.py", line 64, in invokeToneConversation
    updateUserTone(payload, tone, maintainToneHistoryInContext)
  File "C:\Users\diana\assistantandtoneanalyser\tone_detection.py", line 63, in updateUserTone
    for toneCategory in toneAnalyzerPayload['document_tone']['tone_categories']:
KeyError: 'tone_categories'
```

I have passed all the credentials and trying this example with a text :' I am happy' 

Please help 
Thanks in advance

**Comment by ehdsouza** [comment]
Hi @diana-RC, which version of the SDK are you using?

**Comment by diana-RC** [comment]
Thank you for replying. I am using python 2.7

**Comment by ehdsouza** [comment]
Could you also provide which verison of SDK you are using: try with the latest `pip install ibm-watson==3.4.2`

**Comment by diana-RC** [comment]
Hi,
 it is ibm-cloud-sdk-core-0.5.1.  After running pip install ibm-watson==3.4.2 version changed to ibm-cloud-sdk-core-0.5.2(currently)
I am running this example program in windows command line. I have supplied the service credentials directly in the tone_assistant_integration_v1.py.   I tried again running the program . I am getting the same errror.
pls advice
thanks you

**Comment by ehdsouza** [comment]
It looks like your tone analyzer instance is not returning the categories: https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/assistant_tone_analyzer_integration/tone_detection.py#L63
You could print and see what this returns: `toneAnalyzerPayload['document_tone'`

It runs fine for me: ` python examples/assistant_tone_analyzer_integration/tone_assistant_integration.v1.py`
```{
  "entities": [], 
  "intents": [], 
  "output": {
    "generic": [], 
    "text": [], 
    "warning": "No dialog node condition matched to true in the last dialog round - context.nodes_visited is empty. Falling back to the root node in the next round.", 
    "log_messages": [
      {
        "msg": "No dialog node condition matched to true in the last dialog round - context.nodes_visited is empty. Falling back to the root node in the next round.", 
        "level": "warn"
      }
    ], 
    "nodes_visited": []
  }, 
  "context": {
    "conversation_id": "233e23a3-35d1-456f-b8dc-9279af8e41e1", 
    "user": {
      "tone": {
        "emotion": {
          "current": "joy", 
          "history": [
            {
              "tone_name": "joy", 
              "score": 1
            }
          ]
        }, 
        "writing": {
          "current": [], 
          "history": [
            [
              {
                "tone_name": "analytical", 
                "interpretation": "no evidence", 
                "score": 0
              }, 
              {
                "tone_name": "confident", 
                "interpretation": "no evidence", 
                "score": 0
              }, 
              {
                "tone_name": "tentative", 
                "interpretation": "no evidence", 
                "score": 0
              }
            ]
          ]
        }, 
        "social": {
          "current": [
            "openness_low", 
            "emotional range_low", 
            [
              {
                "tone_name": "openness", 
                "interpretation": "likely low", 
                "score": 0.086951
              }, 
              {
                "tone_name": "conscientiousness", 
                "interpretation": "likely medium", 
                "score": 0.270278
              }, 
              {
                "tone_name": "extraversion", 
                "interpretation": "likely medium", 
                "score": 0.512273
              }, 
              {
                "tone_name": "agreeableness", 
                "interpretation": "likely medium", 
                "score": 0.598685
              }, 
              {
                "tone_name": "emotional range", 
                "interpretation": "likely low", 
                "score": 0.174635
              }
            ]
          ]
        }
      }
    }, 
    "system": {
      "dialog_turn_counter": 1, 
      "initialized": true, 
      "dialog_request_counter": 1, 
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ]
    }
  }, 
  "input": {
    "text": "I am happy"
  }
}```

**Comment by diana-RC** [comment]
Hi,
thank you for the reply. I am getting error  after installing pip install ibm-watson==3.4.2

and has ibm-cloud-sdk-core-0.5.2

 from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
ImportError: No module named authenticators

To solve the authenticator error , i tried pip install --upgrade ibm-cloud-sdk-core
 which install ibm-cloud-sdk-core-1.0.0.
then i get an error 

 File "tone_assistant_integration.v1.py", line 6, in <module>
    from ibm_watson import AssistantV1
  File "C:\Python27\lib\site-packages\ibm_watson\__init__.py", line 16, in <module>
    from ibm_cloud_sdk_core import IAMTokenManager, DetailedResponse, BaseService, ApiException
  File "C:\Python27\lib\site-packages\ibm_cloud_sdk_core\__init__.py", line 16, in <module>
    from .base_service import BaseService
  File "C:\Python27\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 136
    response = requests.request(**request, cookies=self.jar, **kwargs)


this is how i am passing the credentials in file tone_assistant_integration.v1.py

# replace with your own assistant credentials or put them in a .env file
assistant_authenticator = IAMAuthenticator('xxxxxxx')
assistant = AssistantV1(
    version='2018-07-10',
    authenticator=assistant_authenticator)

# replace with your own tone analyzer credentials
tone_analyzer_authenticator = IAMAuthenticator('xxxxxxxx')
tone_analyzer = ToneAnalyzerV3(
    version='2016-05-19',
    authenticator=tone_analyzer_authenticator)

# replace with your own workspace_id
workspace_id = 'xxxxxxxx'


Many thanks in advance

**Comment by ehdsouza** [comment]
Your code snippet from master needs the latest that we just released: `4.0.0`. 

If you are using `3.4.2`, please follow: https://github.com/watson-developer-cloud/python-sdk/blob/3.0/examples/assistant_tone_analyzer_integration/tone_assistant_integration.v1.py

**Comment by diana-RC** [comment]
Thank you ehdsouza for patiently answering my issues. Issue is solved . Thanks a lot

**Comment by roshnij** [comment]
I am still getting following error even after installing 4.0.0

`Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from ibm_watson import AssistantV1
  File "/usr/local/lib/python2.7/site-packages/ibm_watson/__init__.py", line 16, in <module>
    from ibm_cloud_sdk_core import IAMTokenManager, DetailedResponse, BaseService, ApiException
  File "/usr/local/lib/python2.7/site-packages/ibm_cloud_sdk_core/__init__.py", line 16, in <module>
    from .base_service import BaseService
  File "/usr/local/lib/python2.7/site-packages/ibm_cloud_sdk_core/base_service.py", line 136
    response = requests.request(**request, cookies=self.jar, **kwargs)
 `
Could you please help me.

**Comment by ehdsouza** [comment]
@roshnij `v4+` releases don't support python `2.7`

**Comment by ehdsouza** [comment]
Closing as per @diana-RC response and @roshnij has a incorrect python version
